<?php
require_once('templates/header.phtml'); ?>
<div id="page-container" class="notClickable">
    <div id="inner-page-container">
        <div id="content-wrap">
            <div class="card cardBody">
                <h1>Our products</h1>
            </div>
            <div class="message d-flex d-inline-flex justify-content-center flex-wrap">
<!--                <p class="alertMessage">New products coming soon..</p>-->
                <div onclick="location.href='not-available';" class="card cardRetail justify-content-center"><p class="indexProducts">Apps</p></div>
                <div onclick="location.href='not-available';" class="card cardRetail justify-content-center"><p class="indexProducts">Games</p></div>
                <div onclick="location.href='not-available';" class="card cardRetail justify-content-center"><p class="indexProducts">Books</p></div>
            </div>
        </div>
    </div>
</div>
<?php require_once('templates/footer.phtml'); ?>

