<?php
require_once('templates/header.phtml'); ?>
    <div id="page-container">
        <div id="inner-page-container">
            <div id="content-wrap">
                <div class="card cardBody">
                    <h1>My purchases</h1>
                </div>
                <div class="message">
                    <p class="alertMessage">List empty</p>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapBackButton">
        <button onclick="location.href='../userHome.php';" class="backButton">Back</button>
    </div>

<?php require_once('templates/footer.phtml'); ?>